INSERT INTO Passenger(Passenger_id, Ticket_id, Special_requests, Passenger_types) VALUES

('CS1', 'T1', 'In-flight meal', 'Youth'),
('CS2', 'T2', 'Priority boarding, Lounge access', 'Child'),
('CS3', 'T3', NULL, 'Adult'),
('CS4', 'T4', 'Extra legroom', 'Adult'),
('CS5', 'T5', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS6', 'T6', NULL, 'Adult'),
('CS7', 'T7', 'Priority boarding', 'Adult'),
('CS8', 'T8', 'Spa access, Personalized service', 'Adult'),
('CS9', 'T9', 'In-flight entertainment', 'Senior'),
('CS10', 'T10', 'Lounge access', 'Senior'),
('CS11', 'T11', 'Fine dining, Personal butler', 'Adult'),
('CS12', 'T12', NULL, 'Adult'),
('CS13', 'T13', 'Priority boarding, Extra legroom', 'Child'),
('CS14', 'T14', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS15', 'T15', 'WiFi service', 'Adult'),
('CS16', 'T16', 'Priority boarding, Lounge access', 'Adult'),
('CS17', 'T17', 'Private suite, Personalized menu', 'Adult'),
('CS18', 'T18', NULL, 'Adult'),
('CS19', 'T19', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS20', 'T20', 'Private cabin, Dedicated staff', 'Senior'),
('CS21', 'T21', 'Extra luggage', 'Youth'),
('CS22', 'T22', 'Priority boarding, Lounge access', 'Senior'),
('CS23', 'T23', 'Private suite, Personalized menu', 'Senior'),
('CS24', 'T24', 'In-flight entertainment', 'Youth'),
('CS25', 'T25', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS26', 'T26', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS27', 'T27', 'WiFi service', 'Adult'),
('CS28', 'T28', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS29', 'T29', 'Private cabin, Dedicated staff', 'Youth'),
('CS30', 'T30', NULL, 'Youth'),
('CS31', 'T31', 'Priority boarding, Lounge access', 'Senior'),
('CS32', 'T32', 'Personalized service, Fine dining', 'Youth'),
('CS33', 'T33', NULL, 'Youth'),
('CS34', 'T34', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS35', 'T35', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS36', 'T36', 'In-flight entertainment', 'Adult'),
('CS37', 'T37', 'Priority boarding, Lounge access', 'Child'),
('CS38', 'T38', 'Private suite, Personalized menu', 'Adult'),
('CS39', 'T39', 'Extra luggage', 'Adult'),
('CS40', 'T40', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS41', 'T41', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS42', 'T42', 'WiFi service', 'Senior'),
('CS43', 'T43', 'Priority boarding, Lounge access', 'Senior'),
('CS44', 'T44', 'Private cabin, Dedicated staff', 'Adult'),
('CS45', 'T45', NULL, 'Youth'),
('CS46', 'T46', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS47', 'T47', 'Personalized service, Fine dining', 'Adult'),
('CS48', 'T48', 'In-flight entertainment', 'Adult'),
('CS49', 'T49', 'Priority boarding, Lounge access', 'Youth'),
('CS50', 'T50', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS51', 'T51', 'Extra luggage', 'Adult'),
('CS52', 'T52', 'Priority boarding, Lounge access', 'Adult'),
('CS53', 'T53', 'Private suite, Personalized menu', 'Adult'),
('CS54', 'T54', 'In-flight entertainment', 'Youth'),
('CS55', 'T55', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS56', 'T56', 'Exclusive lounge access, Personal chef', 'Youth'),
('CS57', 'T57', 'WiFi service', 'Adult'),
('CS58', 'T58', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS59', 'T59', 'Private cabin, Dedicated staff', 'Child'),
('CS60', 'T60', NULL, 'Youth'),
('CS61', 'T61', 'Priority boarding, Lounge access', 'Child'),
('CS62', 'T62', 'Personalized service, Fine dining', 'Adult'),
('CS63', 'T63', NULL, 'Senior'),
('CS64', 'T64', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS65', 'T65', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS66', 'T66', 'In-flight entertainment', 'Youth'),
('CS67', 'T67', 'Priority boarding, Lounge access', 'Senior'),
('CS68', 'T68', 'Private suite, Personalized menu', 'Senior'),
('CS69', 'T69', 'Extra luggage', 'Adult'),
('CS70', 'T70', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS71', 'T71', 'Exclusive lounge access, Personal chef', 'Senior'),
('CS72', 'T72', 'WiFi service', 'Child'),
('CS73', 'T73', 'Priority boarding, Lounge access', 'Youth'),
('CS74', 'T74', 'Private cabin, Dedicated staff', 'Adult'),
('CS75', 'T75', NULL, 'Adult'),
('CS76', 'T76', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS77', 'T77', 'Personalized service, Fine dining', 'Adult'),
('CS78', 'T78', 'In-flight entertainment', 'Child'),
('CS79', 'T79', 'Priority boarding, Lounge access', 'Adult'),
('CS80', 'T80', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS81', 'T81', 'Extra luggage', 'Youth'),
('CS82', 'T82', 'Priority boarding, Lounge access', 'Adult'),
('CS83', 'T83', 'Private suite, Personalized menu', 'Child'),
('CS84', 'T84', 'In-flight entertainment', 'Senior'),
('CS85', 'T85', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS86', 'T86', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS87', 'T87', 'WiFi service', 'Youth'),
('CS88', 'T88', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS89', 'T89', 'Private cabin, Dedicated staff', 'Adult'),
('CS90', 'T90', NULL, 'Senior'),
('CS91', 'T91', 'Priority boarding, Lounge access', 'Adult'),
('CS92', 'T92', 'Personalized service, Fine dining', 'Adult'),
('CS93', 'T93', NULL, 'Adult'),
('CS94', 'T94', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS95', 'T95', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS96', 'T96', 'In-flight entertainment', 'Child'),
('CS97', 'T97', 'Priority boarding, Lounge access', 'Senior'),
('CS98', 'T98', 'Private suite, Personalized menu', 'Child'),
('CS99', 'T99', 'Extra luggage', 'Youth'),
('CS100', 'T100', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS101', 'T101', 'Exclusive lounge access, Personal chef', 'Senior'),
('CS102', 'T102', 'WiFi service', 'Youth'),
('CS103', 'T103', 'Priority boarding, Lounge access', 'Youth'),
('CS104', 'T104', 'Private cabin, Dedicated staff', 'Senior'),
('CS105', 'T105', NULL, 'Adult'),
('CS106', 'T106', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS107', 'T107', 'Personalized service, Fine dining', 'Adult'),
('CS108', 'T108', 'In-flight entertainment', 'Youth'),
('CS109', 'T109', 'Priority boarding, Lounge access', 'Adult'),
('CS110', 'T110', 'Chauffeur service, Gourmet meal', 'Child'),
('CS111', 'T111', 'Extra luggage', 'Adult'),
('CS112', 'T112', 'Priority boarding, Lounge access', 'Child'),
('CS113', 'T113', 'Private suite, Personalized menu', 'Adult'),
('CS114', 'T114', 'In-flight entertainment', 'Adult'),
('CS115', 'T115', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS116', 'T116', 'Exclusive lounge access, Personal chef', 'Senior'),
('CS117', 'T117', 'WiFi service', 'Adult'),
('CS118', 'T118', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS119', 'T119', 'Private cabin, Dedicated staff', 'Adult'),
('CS120', 'T120', NULL, 'Adult'),
('CS121', 'T121', 'Priority boarding, Lounge access', 'Senior'),
('CS122', 'T122', 'Personalized service, Fine dining', 'Senior'),
('CS123', 'T123', NULL, 'Senior'),
('CS124', 'T124', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS125', 'T125', 'Chauffeur service, Gourmet meal', 'Youth'),
('CS126', 'T126', 'In-flight entertainment', 'Adult'),
('CS127', 'T127', 'Priority boarding, Lounge access', 'Adult'),
('CS128', 'T128', 'Private suite, Personalized menu', 'Child'),
('CS129', 'T129', 'Extra luggage', 'Adult'),
('CS130', 'T130', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS131', 'T131', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS132', 'T132', 'WiFi service', 'Youth'),
('CS133', 'T133', 'Priority boarding, Lounge access', 'Senior'),
('CS134', 'T134', 'Private cabin, Dedicated staff', 'Adult'),
('CS135', 'T135', NULL, 'Adult'),
('CS136', 'T136', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS137', 'T137', 'Personalized service, Fine dining', 'Youth'),
('CS138', 'T138', 'In-flight entertainment', 'Youth'),
('CS139', 'T139', 'Priority boarding, Lounge access', 'Adult'),
('CS140', 'T140', 'Chauffeur service, Gourmet meal', 'Youth'),
('CS141', 'T141', 'Extra luggage', 'Adult'),
('CS142', 'T142', 'Priority boarding, Lounge access', 'Senior'),
('CS143', 'T143', 'Private suite, Personalized menu', 'Adult'),
('CS144', 'T144', 'In-flight entertainment', 'Senior'),
('CS145', 'T145', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS146', 'T146', 'Exclusive lounge access, Personal chef', 'Senior'),
('CS147', 'T147', 'WiFi service', 'Adult'),
('CS148', 'T148', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS149', 'T149', 'Private cabin, Dedicated staff', 'Adult'),
('CS150', 'T150', NULL, 'Adult'),
('CS151', 'T151', 'Priority boarding, Lounge access', 'Child'),
('CS152', 'T152', 'Personalized service, Fine dining', 'Youth'),
('CS153', 'T153', NULL, 'Adult'),
('CS154', 'T154', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS155', 'T155', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS156', 'T156', 'In-flight entertainment', 'Senior'),
('CS157', 'T157', 'Priority boarding, Lounge access', 'Adult'),
('CS158', 'T158', 'Private suite, Personalized menu', 'Adult'),
('CS159', 'T159', 'Extra luggage', 'Adult'),
('CS160', 'T160', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS161', 'T161', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS162', 'T162', 'WiFi service', 'Senior'),
('CS163', 'T163', 'Priority boarding, Lounge access', 'Youth'),
('CS164', 'T164', 'Private cabin, Dedicated staff', 'Adult'),
('CS165', 'T165', NULL, 'Adult'),
('CS166', 'T166', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS167', 'T167', 'Personalized service, Fine dining', 'Child'),
('CS168', 'T168', 'In-flight entertainment', 'Youth'),
('CS169', 'T169', 'Priority boarding, Lounge access', 'Adult'),
('CS170', 'T170', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS171', 'T171', 'Extra luggage', 'Child'),
('CS172', 'T172', 'Priority boarding, Lounge access', 'Youth'),
('CS173', 'T173', 'Private suite, Personalized menu', 'Youth'),
('CS174', 'T174', 'In-flight entertainment', 'Adult'),
('CS175', 'T175', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS176', 'T176', 'Exclusive lounge access, Personal chef', 'Child'),
('CS177', 'T177', 'WiFi service', 'Senior'),
('CS178', 'T178', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS179', 'T179', 'Private cabin, Dedicated staff', 'Adult'),
('CS180', 'T180', NULL, 'Adult'),
('CS181', 'T181', 'Priority boarding, Lounge access', 'Child'),
('CS182', 'T182', 'Personalized service, Fine dining', 'Adult'),
('CS183', 'T183', NULL, 'Youth'),
('CS184', 'T184', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS185', 'T185', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS186', 'T186', 'In-flight entertainment', 'Youth'),
('CS187', 'T187', 'Priority boarding, Lounge access', 'Adult'),
('CS188', 'T188', 'Private suite, Personalized menu', 'Adult'),
('CS189', 'T189', 'Extra luggage', 'Youth'),
('CS190', 'T190', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS191', 'T191', 'Exclusive lounge access, Personal chef', 'Child'),
('CS192', 'T192', 'WiFi service', 'Adult'),
('CS193', 'T193', 'Priority boarding, Lounge access', 'Adult'),
('CS194', 'T194', 'Private cabin, Dedicated staff', 'Adult'),
('CS195', 'T195', NULL, 'Youth'),
('CS196', 'T196', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS197', 'T197', 'Personalized service, Fine dining', 'Adult'),
('CS198', 'T198', 'In-flight entertainment', 'Child'),
('CS199', 'T199', 'Priority boarding, Lounge access', 'Senior'),
('CS200', 'T200', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS201', 'T201', 'Extra luggage', 'Adult'),
('CS202', 'T202', 'Priority boarding, Lounge access', 'Adult'),
('CS203', 'T203', 'Private suite, Personalized menu', 'Youth'),
('CS204', 'T204', 'In-flight entertainment', 'Senior'),
('CS205', 'T205', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS206', 'T206', 'Exclusive lounge access, Personal chef', 'Child'),
('CS207', 'T207', 'WiFi service', 'Adult'),
('CS208', 'T208', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS209', 'T209', 'Private cabin, Dedicated staff', 'Youth'),
('CS210', 'T210', NULL, 'Adult'),
('CS211', 'T211', 'Priority boarding, Lounge access', 'Adult'),
('CS212', 'T212', 'Personalized service, Fine dining', 'Youth'),
('CS213', 'T213', NULL, 'Adult'),
('CS214', 'T214', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS215', 'T215', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS216', 'T216', 'In-flight entertainment', 'Senior'),
('CS217', 'T217', 'Priority boarding, Lounge access', 'Adult'),
('CS218', 'T218', 'Private suite, Personalized menu', 'Child'),
('CS219', 'T219', 'Extra luggage', 'Adult'),
('CS220', 'T220', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS221', 'T221', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS222', 'T222', 'WiFi service', 'Adult'),
('CS223', 'T223', 'Priority boarding, Lounge access', 'Adult'),
('CS224', 'T224', 'Private cabin, Dedicated staff', 'Youth'),
('CS225', 'T225', NULL, 'Child'),
('CS226', 'T226', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS227', 'T227', 'Personalized service, Fine dining', 'Senior'),
('CS228', 'T228', 'In-flight entertainment', 'Senior'),
('CS229', 'T229', 'Priority boarding, Lounge access', 'Child'),
('CS230', 'T230', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS231', 'T231', 'Extra luggage', 'Adult'),
('CS232', 'T232', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS233', 'T233', 'Private suite, Personalized menu', 'Adult'),
('CS234', 'T234', 'In-flight entertainment', 'Youth'),
('CS235', 'T235', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS236', 'T236', 'Exclusive lounge access, Personal chef', 'Youth'),
('CS237', 'T237', 'WiFi service', 'Adult'),
('CS238', 'T238', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS239', 'T239', 'Private cabin, Dedicated staff', 'Adult'),
('CS240', 'T240', NULL, 'Adult'),
('CS241', 'T241', 'Priority boarding, Lounge access', 'Adult'),
('CS242', 'T242', 'Personalized service, Fine dining', 'Adult'),
('CS243', 'T243', NULL, 'Adult'),
('CS244', 'T244', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS245', 'T245', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS246', 'T246', 'In-flight entertainment', 'Adult'),
('CS247', 'T247', 'Priority boarding, Lounge access', 'Youth'),
('CS248', 'T248', 'Private suite, Personalized menu', 'Youth'),
('CS249', 'T249', 'Extra luggage', 'Adult'),
('CS250', 'T250', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS251', 'T251', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS252', 'T252', 'WiFi service', 'Child'),
('CS253', 'T253', 'Priority boarding, Lounge access', 'Adult'),
('CS254', 'T254', 'Private cabin, Dedicated staff', 'Adult'),
('CS255', 'T255', NULL, 'Adult'),
('CS256', 'T256', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS257', 'T257', 'Personalized service, Fine dining', 'Child'),
('CS258', 'T258', 'In-flight entertainment', 'Adult'),
('CS259', 'T259', 'Priority boarding, Lounge access', 'Senior'),
('CS260', 'T260', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS261', 'T261', 'Extra luggage', 'Youth'),
('CS262', 'T262', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS263', 'T263', 'Private suite, Personalized menu', 'Youth'),
('CS264', 'T264', 'In-flight entertainment', 'Child'),
('CS265', 'T265', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS266', 'T266', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS267', 'T267', 'WiFi service', 'Adult'),
('CS268', 'T268', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS269', 'T269', 'Private cabin, Dedicated staff', 'Child'),
('CS270', 'T270', NULL, 'Youth'),
('CS271', 'T271', 'Priority boarding, Lounge access', 'Child'),
('CS272', 'T272', 'Personalized service, Fine dining', 'Youth'),
('CS273', 'T273', NULL, 'Adult'),
('CS274', 'T274', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS275', 'T275', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS276', 'T276', 'In-flight entertainment', 'Senior'),
('CS277', 'T277', 'Priority boarding, Lounge access', 'Youth'),
('CS278', 'T278', 'Private suite, Personalized menu', 'Senior'),
('CS279', 'T279', 'Extra luggage', 'Adult'),
('CS280', 'T280', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS281', 'T281', 'Exclusive lounge access, Personal chef', 'Child'),
('CS282', 'T282', 'WiFi service', 'Senior'),
('CS283', 'T283', 'Priority boarding, Lounge access', 'Adult'),
('CS284', 'T284', 'Private cabin, Dedicated staff', 'Adult'),
('CS285', 'T285', NULL, 'Youth'),
('CS286', 'T286', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS287', 'T287', 'Personalized service, Fine dining', 'Youth'),
('CS288', 'T288', 'In-flight entertainment', 'Adult'),
('CS289', 'T289', 'Priority boarding, Lounge access', 'Adult'),
('CS290', 'T290', 'Chauffeur service, Gourmet meal', 'Youth'),
('CS291', 'T291', 'Extra luggage', 'Youth'),
('CS292', 'T292', 'Priority boarding, Lounge access', 'Youth'),
('CS293', 'T293', 'Private suite, Personalized menu', 'Adult'),
('CS294', 'T294', 'In-flight entertainment', 'Adult'),
('CS295', 'T295', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS296', 'T296', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS297', 'T297', 'WiFi service', 'Child'),
('CS298', 'T298', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS299', 'T299', 'Private cabin, Dedicated staff', 'Child'),
('CS300', 'T300', NULL, 'Adult'),
('CS301', 'T301', 'Priority boarding, Lounge access', 'Senior'),
('CS302', 'T302', 'Personalized service, Fine dining', 'Adult'),
('CS303', 'T303', NULL, 'Child'),
('CS304', 'T304', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS305', 'T305', 'Chauffeur service, Gourmet meal', 'Child'),
('CS306', 'T306', 'In-flight entertainment', 'Adult'),
('CS307', 'T307', 'Priority boarding, Lounge access', 'Adult'),
('CS308', 'T308', 'Private suite, Personalized menu', 'Adult'),
('CS309', 'T309', 'Extra luggage', 'Child'),
('CS310', 'T310', 'Priority boarding, Extra legroom, Lounge access', 'Senior'),
('CS311', 'T311', 'Exclusive lounge access, Personal chef', 'Youth'),
('CS312', 'T312', 'WiFi service', 'Adult'),
('CS313', 'T313', 'Priority boarding, Lounge access', 'Adult'),
('CS314', 'T314', 'Private cabin, Dedicated staff', 'Adult'),
('CS315', 'T315', NULL, 'Youth'),
('CS316', 'T316', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS317', 'T317', 'Personalized service, Fine dining', 'Youth'),
('CS318', 'T318', 'In-flight entertainment', 'Senior'),
('CS319', 'T319', 'Priority boarding, Lounge access', 'Youth'),
('CS320', 'T320', 'Chauffeur service, Gourmet meal', 'Child'),
('CS321', 'T321', 'Extra luggage', 'Adult'),
('CS322', 'T322', 'Priority boarding, Lounge access', 'Adult'),
('CS323', 'T323', 'Private suite, Personalized menu', 'Child'),
('CS324', 'T324', 'In-flight entertainment', 'Adult'),
('CS325', 'T325', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS326', 'T326', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS327', 'T327', 'WiFi service', 'Adult'),
('CS328', 'T328', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS329', 'T329', 'Private cabin, Dedicated staff', 'Senior'),
('CS330', 'T330', NULL, 'Child'),
('CS331', 'T331', 'Priority boarding, Lounge access', 'Adult'),
('CS332', 'T332', 'Personalized service, Fine dining', 'Youth'),
('CS333', 'T333', 'In-flight entertainment', 'Adult'),
('CS334', 'T334', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS335', 'T335', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS336', 'T336', 'Extra luggage', 'Child'),
('CS337', 'T337', 'Priority boarding, Lounge access', 'Adult'),
('CS338', 'T338', 'Private suite, Personalized menu', 'Adult'),
('CS339', 'T339', 'WiFi service', 'Adult'),
('CS340', 'T340', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS341', 'T341', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS342', 'T342', NULL, 'Youth'),
('CS343', 'T343', 'Priority boarding, Lounge access', 'Adult'),
('CS344', 'T344', 'Private cabin, Dedicated staff', 'Adult'),
('CS345', 'T345', 'Extra luggage', 'Adult'),
('CS346', 'T346', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS347', 'T347', 'Personalized service, Fine dining', 'Adult'),
('CS348', 'T348', 'In-flight entertainment', 'Adult'),
('CS349', 'T349', 'Priority boarding, Lounge access', 'Senior'),
('CS350', 'T350', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS351', 'T351', 'Extra luggage', 'Adult'),
('CS352', 'T352', 'Priority boarding, Lounge access', 'Adult'),
('CS353', 'T353', 'Private suite, Personalized menu', 'Adult'),
('CS354', 'T354', 'In-flight entertainment', 'Adult'),
('CS355', 'T355', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS356', 'T356', 'Exclusive lounge access, Personal chef', 'Senior'),
('CS357', 'T357', 'WiFi service', 'Adult'),
('CS358', 'T358', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS359', 'T359', 'Private cabin, Dedicated staff', 'Adult'),
('CS360', 'T360', NULL, 'Youth'),
('CS361', 'T361', 'Priority boarding, Lounge access', 'Adult'),
('CS362', 'T362', 'Personalized service, Fine dining', 'Youth'),
('CS363', 'T363', NULL, 'Youth'),
('CS364', 'T364', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS365', 'T365', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS366', 'T366', 'In-flight entertainment', 'Child'),
('CS367', 'T367', 'Priority boarding, Lounge access', 'Child'),
('CS368', 'T368', 'Private suite, Personalized menu', 'Adult'),
('CS369', 'T369', 'Extra luggage', 'Senior'),
('CS370', 'T370', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS371', 'T371', 'Exclusive lounge access, Personal chef', 'Youth'),
('CS372', 'T372', 'WiFi service', 'Adult'),
('CS373', 'T373', 'Priority boarding, Lounge access', 'Adult'),
('CS374', 'T374', 'Private cabin, Dedicated staff', 'Child'),
('CS375', 'T375', NULL, 'Adult'),
('CS376', 'T376', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS377', 'T377', 'Personalized service, Fine dining', 'Adult'),
('CS378', 'T378', 'In-flight entertainment', 'Adult'),
('CS379', 'T379', 'Priority boarding, Lounge access', 'Adult'),
('CS380', 'T380', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS381', 'T381', 'Extra luggage', 'Adult'),
('CS382', 'T382', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS383', 'T383', 'Private suite, Personalized menu', 'Adult'),
('CS384', 'T384', 'WiFi service', 'Child'),
('CS385', 'T385', 'Priority boarding, Lounge access', 'Child'),
('CS386', 'T386', 'Exclusive lounge access, Personal chef', 'Youth'),
('CS387', 'T387', 'In-flight entertainment', 'Senior'),
('CS388', 'T388', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS389', 'T389', 'Private cabin, Dedicated staff', 'Adult'),
('CS390', 'T390', NULL, 'Adult'),
('CS391', 'T391', 'Priority boarding, Lounge access', 'Youth'),
('CS392', 'T392', 'Personalized service, Fine dining', 'Adult'),
('CS393', 'T393', 'In-flight entertainment', 'Senior'),
('CS394', 'T394', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS395', 'T395', 'Chauffeur service, Gourmet meal', 'Senior'),
('CS396', 'T396', 'Extra luggage', 'Adult'),
('CS397', 'T397', 'Priority boarding, Lounge access', 'Youth'),
('CS398', 'T398', 'Private suite, Personalized menu', 'Senior'),
('CS399', 'T399', 'WiFi service', 'Youth'),
('CS400', 'T400', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS401', 'T401', 'Extra luggage', 'Adult'),
('CS402', 'T402', 'Priority boarding, Lounge access', 'Adult'),
('CS403', 'T403', 'Private suite, Personalized menu', 'Adult'),
('CS404', 'T404', 'In-flight entertainment', 'Senior'),
('CS405', 'T405', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS406', 'T406', 'Exclusive lounge access, Personal chef', 'Adult'),
('CS407', 'T407', 'WiFi service', 'Adult'),
('CS408', 'T408', 'Priority boarding, Extra legroom, Lounge access', 'Child'),
('CS409', 'T409', 'Private cabin, Dedicated staff', 'Youth'),
('CS410', 'T410', NULL, 'Child'),
('CS411', 'T411', 'Priority boarding, Lounge access', 'Adult'),
('CS412', 'T412', 'Personalized service, Fine dining', 'Youth'),
('CS413', 'T413', 'In-flight entertainment', 'Adult'),
('CS414', 'T414', 'Priority boarding, Extra legroom, Lounge access', 'Youth'),
('CS415', 'T415', 'Chauffeur service, Gourmet meal', 'Adult'),
('CS416', 'T416', 'Extra luggage', 'Adult'),
('CS417', 'T417', 'Priority boarding, Lounge access', 'Child'),
('CS418', 'T418', 'Private suite, Personalized menu', 'Adult'),
('CS419', 'T419', 'WiFi service', 'Adult'),
('CS420', 'T420', 'Priority boarding, Extra legroom, Lounge access', 'Adult'),
('CS421', 'T421', NULL, 'Child'),
('CS422', 'T422', 'Baggage Check', 'Child'),
('CS423', 'T423', 'In-flight Entertainment', 'Senior'),
('CS424', 'T424', NULL, 'Youth'),
('CS425', 'T425', 'Priority Boarding', 'Adult'),
('CS426', 'T426', 'In-flight Meal', 'Youth'),
('CS427', 'T427', NULL, 'Adult'),
('CS428', 'T428', 'Baggage Check', 'Adult'),
('CS429', 'T429', 'Priority Boarding', 'Adult'),
('CS430', 'T430', 'Baggage Check', 'Child'),
('CS431', 'T431', 'In-flight Meal', 'Adult'),
('CS432', 'T432', 'In-flight Entertainment', 'Youth'),
('CS433', 'T433', NULL, 'Child'),
('CS434', 'T434', 'Priority Boarding', 'Adult'),
('CS435', 'T435', 'In-flight Meal', 'Adult'),
('CS436', 'T436', NULL, 'Child'),
('CS437', 'T437', 'Baggage Check', 'Senior'),
('CS438', 'T438', 'In-flight Entertainment', 'Child'),
('CS439', 'T439', NULL, 'Child'),
('CS440', 'T440', 'In-flight Meal', 'Adult'),
('CS441', 'T441', 'Priority Boarding', 'Senior'),
('CS442', 'T442', NULL, 'Youth'),
('CS443', 'T443', 'Baggage Check', 'Adult'),
('CS444', 'T444', 'In-flight Entertainment', 'Youth'),
('CS445', 'T445', NULL, 'Adult'),
('CS446', 'T446', 'In-flight Meal', 'Adult'),
('CS447', 'T447', 'Priority Boarding', 'Senior'),
('CS448', 'T448', NULL, 'Child'),
('CS449', 'T449', 'Baggage Check', 'Adult'),
('CS450', 'T450', 'In-flight Entertainment', 'Youth'),
('CS451', 'T451', NULL, 'Adult'),
('CS452', 'T452', 'In-flight Meal', 'Senior'),
('CS453', 'T453', 'Priority Boarding', 'Adult'),
('CS454', 'T454', NULL, 'Adult'),
('CS455', 'T455', 'Baggage Check', 'Adult'),
('CS456', 'T456', 'In-flight Entertainment', 'Adult'),
('CS457', 'T457', NULL, 'Adult'),
('CS458', 'T458', 'In-flight Meal', 'Adult'),
('CS459', 'T459', 'Priority Boarding', 'Adult'),
('CS460', 'T460', NULL, 'Senior'),
('CS461', 'T461', 'Baggage Check', 'Adult'),
('CS462', 'T462', 'In-flight Entertainment', 'Youth'),
('CS463', 'T463', NULL, 'Adult'),
('CS464', 'T464', 'In-flight Meal', 'Adult'),
('CS465', 'T465', 'Priority Boarding', 'Adult'),
('CS466', 'T466', NULL, 'Child'),
('CS467', 'T467', 'Baggage Check', 'Child'),
('CS468', 'T468', 'In-flight Entertainment', 'Child'),
('CS469', 'T469', NULL, 'Child'),
('CS470', 'T470', 'In-flight Meal', 'Adult'),
('CS471', 'T471', 'Priority Boarding', 'Senior'),
('CS472', 'T472', NULL, 'Child'),
('CS473', 'T473', 'Baggage Check', 'Youth'),
('CS474', 'T474', 'In-flight Entertainment', 'Youth'),
('CS475', 'T475', NULL, 'Adult'),
('CS476', 'T476', 'In-flight Meal', 'Child'),
('CS477', 'T477', 'Priority Boarding', 'Adult'),
('CS478', 'T478', NULL, 'Child'),
('CS479', 'T479', 'Baggage Check', 'Youth'),
('CS480', 'T480', 'In-flight Entertainment', 'Adult'),
('CS481', 'T481', NULL, 'Senior'),
('CS482', 'T482', 'In-flight Meal', 'Adult'),
('CS483', 'T483', 'Priority Boarding', 'Adult'),
('CS484', 'T484', NULL, 'Adult'),
('CS485', 'T485', 'Baggage Check', 'Adult'),
('CS486', 'T486', 'In-flight Entertainment', 'Adult'),
('CS487', 'T487', NULL, 'Child'),
('CS488', 'T488', 'In-flight Meal', 'Adult'),
('CS489', 'T489', 'Priority Boarding', 'Senior'),
('CS490', 'T490', 'Baggage Check', 'Adult'),
('CS491', 'T491', 'In-flight Entertainment', 'Adult'),
('CS492', 'T492', 'In-flight Meal', 'Youth'),
('CS493', 'T493', NULL, 'Youth'),
('CS494', 'T494', 'Priority Boarding', 'Adult'),
('CS495', 'T495', 'In-flight Entertainment', 'Adult'),
('CS496', 'T496', NULL, 'Senior'),
('CS497', 'T497', 'Baggage Check', 'Youth'),
('CS498', 'T498', 'In-flight Meal', 'Adult'),
('CS499', 'T499', NULL, 'Adult'),
('CS500', 'T500', 'In-flight Entertainment', 'Adult');






